debug1

diff --git a/.github/workflows/qa_l0_pytorch.yml b/.github/workflows/qa_l0_pytorch.yml
--- a/.github/workflows/qa_l0_pytorch.yml
+++ b/.github/workflows/qa_l0_pytorch.yml
@@ -110,6 +110,7 @@ jobs:
       #     ctest --test-dir build -j$NUM_PARALLEL_JOBS
 
       - name: L0_pytorch_debug_unittest
+        id: L0_pytorch_debug_unittest
         env:
           PYTEST_ADDOPTS: "-v -s"
           NVTE_TEST_NVINSPECT_FEATURE_DIRS: "transformer_engine/debug/features"
@@ -117,25 +118,48 @@ jobs:
           NVTE_TEST_NVINSPECT_DUMMY_CONFIG_FILE: "tests/pytorch/debug/test_configs/dummy_feature.yaml"
           XML_LOG_DIR: "/logs/pytorch/debug"
         run: |
-          echo "XML_LOG_DIR: ${XML_LOG_DIR}"
+          # Build log storage directory
+          mkdir -p "$XML_LOG_DIR"
+
+          # It is not installed as a requirement,
+          # because it is not available on PyPI.
+          pip uninstall -y nvdlfw-inspect
+          pip install git+https://github.com/NVIDIA/nvidia-dlfw-inspect.git
+          pip install pytest==8.2.1
+
+          run_pytest() {
+            local test_file=$1
+            local xml_name=$2
+            local extra_opts=${3:-""}
+            echo "🚀 Running test: $test_file"
+            pytest --junitxml="${XML_LOG_DIR}/${xml_name}" "${test_file}" "${extra_opts}"
+            if [ $? -eq 0 ]; then
+              echo "✅ Test $"xml_name" passed"
+            else
+              echo "❌ Test $"xml_name" failed"
+              exit 1
+            fi
+          }
+
+          # tests/pytorch/debug
+          run_pytest "tests/pytorch/debug/test_sanity.py" "test_sanity.xml" "--feature_dirs=$NVTE_TEST_NVINSPECT_FEATURE_DIRS"
+          run_pytest "tests/pytorch/debug/test_config.py" "test_config.xml" "--feature_dirs=$NVTE_TEST_NVINSPECT_FEATURE_DIRS"
+          run_pytest "tests/pytorch/debug/test_numerics.py" "test_numerics.xml" "--feature_dirs=$NVTE_TEST_NVINSPECT_FEATURE_DIRS"
+          run_pytest "tests/pytorch/debug/test_log.py" "test_log.xml" "--feature_dirs=$NVTE_TEST_NVINSPECT_FEATURE_DIRS --configs_dir=$NVTE_TEST_NVINSPECT_CONFIGS_DIR"
+          run_pytest "tests/pytorch/debug/test_perf.py" "test_perf.xml" "--feature_dirs=$NVTE_TEST_NVINSPECT_FEATURE_DIRS --configs_dir=$NVTE_TEST_NVINSPECT_CONFIGS_DIR"
+          # NVTE_TORCH_COMPILE=0 run_pytest "tests/pytorch/debug/test_api_features.py" "test_api_features.xml" "--feature_dirs=$NVTE_TEST_NVINSPECT_FEATURE_DIRS --configs_dir=$NVTE_TEST_NVINSPECT_CONFIGS_DIR"
 
 
-          # mkdir -p "$XML_LOG_DIR"
+          # standard sanity and numerics tests with initialized debug
+          NVTE_TEST_NVINSPECT_ENABLED=1 NVTE_TEST_NVINSPECT_CONFIG_FILE=$NVTE_TEST_NVINSPECT_DUMMY_CONFIG_FILE NVTE_TEST_NVINSPECT_FEATURE_DIRS=$NVTE_TEST_NVINSPECT_FEATURE_DIRS PYTORCH_JIT=0 NVTE_TORCH_COMPILE=0 NVTE_ALLOW_NONDETERMINISTIC_ALGO=0 pytest --junitxml=$XML_LOG_DIR/test_sanity_2.xml tests/pytorch/test_sanity.py
+          # NVTE_TEST_NVINSPECT_ENABLED=1 NVTE_TEST_NVINSPECT_CONFIG_FILE=$NVTE_TEST_NVINSPECT_DUMMY_CONFIG_FILE NVTE_TEST_NVINSPECT_FEATURE_DIRS=$NVTE_TEST_NVINSPECT_FEATURE_DIRS PYTORCH_JIT=0 NVTE_TORCH_COMPILE=0 NVTE_ALLOW_NONDETERMINISTIC_ALGO=0 NVTE_FUSED_ATTN=0 pytest --junitxml=$XML_LOG_DIR/test_numerics_2.xml tests/pytorch/test_numerics.py
 
-          # # It is not installed as a requirement,
-          # # because it is not available on PyPI.
-          # pip uninstall -y nvdlfw-inspect
-          # pip install git+https://github.com/NVIDIA/nvidia-dlfw-inspect.git
-          # pip install pytest==8.2.1
-
-          # pytest -v -s --junitxml=$XML_LOG_DIR/test_sanity.xml tests/pytorch/debug/test_sanity.py  --feature_dirs=$NVTE_TEST_NVINSPECT_FEATURE_DIRS || FAIL=1
-          # pytest -v -s --junitxml=$XML_LOG_DIR/test_config.xml tests/pytorch/debug/test_config.py --feature_dirs=$NVTE_TEST_NVINSPECT_FEATURE_DIRS || FAIL=1
-          # pytest -v -s --junitxml=$XML_LOG_DIR/test_numerics.xml tests/pytorch/debug/test_numerics.py --feature_dirs=$NVTE_TEST_NVINSPECT_FEATURE_DIRS || FAIL=1
-          # pytest -v -s --junitxml=$XML_LOG_DIR/test_log.xml tests/pytorch/debug/test_log.py --feature_dirs=$NVTE_TEST_NVINSPECT_FEATURE_DIRS --configs_dir=$NVTE_TEST_NVINSPECT_CONFIGS_DIR || FAIL=1
-          # # NVTE_TORCH_COMPILE=0 pytest -v -s --junitxml=$XML_LOG_DIR/test_api_features.xml tests/pytorch/debug/test_api_features.py --feature_dirs=$NVTE_TEST_NVINSPECT_FEATURE_DIRS --configs_dir=$NVTE_TEST_NVINSPECT_CONFIGS_DIR || FAIL=1
-          # pytest -v -s --junitxml=$XML_LOG_DIR/test_perf.xml tests/pytorch/debug/test_perf.py --feature_dirs=$NVTE_TEST_NVINSPECT_FEATURE_DIRS --configs_dir=$NVTE_TEST_NVINSPECT_CONFIGS_DIR || FAIL=1
-
-          # # standard sanity and numerics tests with initialized debug
-          # NVTE_TEST_NVINSPECT_ENABLED=1 NVTE_TEST_NVINSPECT_CONFIG_FILE=$NVTE_TEST_NVINSPECT_DUMMY_CONFIG_FILE NVTE_TEST_NVINSPECT_FEATURE_DIRS=$NVTE_TEST_NVINSPECT_FEATURE_DIRS PYTORCH_JIT=0 NVTE_TORCH_COMPILE=0 NVTE_ALLOW_NONDETERMINISTIC_ALGO=0 pytest -v -s --junitxml=$XML_LOG_DIR/test_sanity_2.xml tests/pytorch/test_sanity.py || FAIL=1
-          # # NVTE_TEST_NVINSPECT_ENABLED=1 NVTE_TEST_NVINSPECT_CONFIG_FILE=$NVTE_TEST_NVINSPECT_DUMMY_CONFIG_FILE NVTE_TEST_NVINSPECT_FEATURE_DIRS=$NVTE_TEST_NVINSPECT_FEATURE_DIRS PYTORCH_JIT=0 NVTE_TORCH_COMPILE=0 NVTE_ALLOW_NONDETERMINISTIC_ALGO=0 NVTE_FUSED_ATTN=0 pytest -v -s --junitxml=$XML_LOG_DIR/test_numerics_2.xml tests/pytorch/test_numerics.py || FAIL=1
-
+      - name: Upload Installation Logs
+        if: failure() && steps.L0_pytorch_debug_unittest.outcome == 'failure'
+        uses: actions/upload-artifact@v4
+        with:
+          name: L0_pytorch-logs-${{ github.run_id }}
+          path: /logs
+          retention-days: 7
+          if-no-files-found: warn
+        continue-on-error: true
