delete original te & install transformer_engine_metax

diff --git a/.github/workflows/unit_tests_common.yml b/.github/workflows/unit_tests_common.yml
--- a/.github/workflows/unit_tests_common.yml
+++ b/.github/workflows/unit_tests_common.yml
@@ -130,8 +130,8 @@ jobs:
       - name: Environment Setup
         if: steps.should_run.outputs.should_run == 'true'
         env:
-          # TE_FL_SKIP_CUDA: '1' 
-          # SKIP_CUDA_BUILD: '1'
+          TE_FL_SKIP_CUDA: '1' 
+          SKIP_CUDA_BUILD: '1'
           NVTE_WITH_MACA: '1'
           NVTE_WITH_CUDA: '0'
 
@@ -146,12 +146,11 @@ jobs:
 
           set -euo pipefail
           # 1. Execute hardware-specific setup (e.g. conda activate, export paths)
+          #! setup_commands from all_tests_xxx.yml(like all_tests_metax.yml) 
+          ${{ inputs.setup_commands }}
           
           #install git when setpu
           apt-get update && apt-get install -y -qq git
-
-          #! setup_commands from all_tests_xxx.yml(like all_tests_metax.yml) 
-          ${{ inputs.setup_commands }}
 
           python3 -m pip install --no-cache-dir cmake ninja --no-deps
           cmake --version
@@ -163,6 +162,29 @@ jobs:
           # 2. Universal dependency sync using the activated python environment
           python3 -m pip install --no-cache-dir transformers expecttest boto3==1.42.1 --no-deps || true
           python3 -m pip install -v -e . --no-deps --no-build-isolation
+
+          # delete original te
+          pip uninstall transformer_engine -y || true
+          
+          # check te metax
+          pip list | grep transformer_engine_metax 
+
+          # install transformer_engine_metax
+          WHL_PATH="/home/muxiuser/transformer_engine_metax-2.9.0-cp312-cp312-linux_x86_64.whl"
+          
+          if [ -f "$WHL_PATH" ]; then
+            echo "Installing Metax CP312 base package..."
+            python3 -m pip install "$WHL_PATH" --force-reinstall
+          else
+            echo "ERROR: Cannot find $WHL_PATH! Please ensure this file is mounted into the container."
+            exit 1
+          fi
+
+          python3 -c "import transformer_engine_torch; print('Binary backend loaded successfully')"
+          
+          cd $GITHUB_WORKSPACE
+          python3 setup.py install
+
         # more time needed...
         timeout-minutes: 120
 
